### PR TITLE
better scaling

### PR DESCRIPTION
**Pull request by hajimehoshi**
This change uses a scaled window size with a fix logical screen size in order to let Ebitengine do a better scaling.

Updates #24
Updates hajimehoshi/ebiten#2951

### CODE REVIEW

**Comment by hajimehoshi** [comment]
image

**Comment by DarkReaper231** [comment]
Can confirm this fixes the issue for both scale 1
image
and fractional values
image

**Comment by hajimehoshi** [comment]
This PR focues on a rendering quality and doesn't resolve the issue at https://github.com/hajimehoshi/ebiten/issues/2951.

**Comment by DarkReaper231** [comment]
> This PR focues on a rendering quality and doesn't resolve the issue at [hajimehoshi/ebiten#2951](https://github.com/hajimehoshi/ebiten/issues/2951) yet.

Oh, makes sense then

**Review by crgimenes — APPROVED** [review]
Excellent! Thanks for your help!
It will be helpful in another project I'm working on!

**Pull request merged**
